AllCops:
  Exclude:
    - lib/rails_stuff/generators/*/templates/*.rb
    - tmp/**/*
Rails: {Enabled: true}

Layout/AlignParameters:
  # Disable, till rubocop supports combination of styles.
  # Use one of this styles where appropriate, keep it clean, compact and readable.
  Enabled: false
  # EnforcedStyle:
  # - with_first_parameter
  # - with_fixed_indentation

# Breaks
#
#   I18n.t(key,
#     param: val,
#     # ...
#   )
Layout/ClosingParenthesisIndentation: {Enabled: false}
Layout/DotPosition: {EnforcedStyle: trailing}
# Same as Layout/ClosingParenthesisIndentation
Layout/MultilineMethodCallBraceLayout: {Enabled: false}
Layout/MultilineMethodCallIndentation: {EnforcedStyle: indented}
Layout/MultilineOperationIndentation: {EnforcedStyle: indented}
Layout/SpaceInsideHashLiteralBraces: {EnforcedStyle: no_space}

# Offences named scopes and `expect {}.to change {}`.
Lint/AmbiguousBlockAssociation: {Enabled: false}

# We use it in describe messages.
Lint/InterpolationCheck:
  Exclude:
  - spec/**/*

Naming/PredicateName: {Enabled: false}
Naming/VariableNumber: {EnforcedStyle: snake_case}

Style/Alias: {Enabled: false}
Style/Documentation: {Enabled: false}
Style/IfUnlessModifier: {Enabled: false}
Style/GuardClause: {Enabled: false}
Style/Lambda: {Enabled: false}
Style/ModuleFunction: {Enabled: false}
Style/NestedParenthesizedCalls: {Enabled: false}
Style/SignalException: {EnforcedStyle: only_raise}
Style/TrailingCommaInArguments: {Enabled: false}
Style/TrailingCommaInLiteral: {EnforcedStyleForMultiline: comma}

Metrics/AbcSize: {Max: 21}
# Other metrics are just enough.
# This one offences all specs, routes and some initializers.
Metrics/BlockLength: {Enabled: false}
Metrics/LineLength: {Max: 100}
Metrics/MethodLength: {Max: 30}
